  truncate table FirebaseUsersData
  delete from [anowakowski_retrodb].[anowakowski_retrousr].[CurrentUserInRetroBoards]
  truncate table CurrentUserVotes
  truncate table MergedRetroBoardCards
  truncate table RetroBoardActionCards
  truncate table RetroBoardAdditionalInfos
  delete from RetroBoardCards
  delete from RetroBoardCardMergedGroups
  truncate table RetroBoards
  truncate table RetroBoardOptions
  truncate table RetroBoardStatuses
  delete from userWaitingToApproveWorkspaceJoins
  truncate table UserNotificationWorkspaceWithRequiredAccessResponses
  truncate table UserNotificationWorkspaceWithRequiredAccesses
  delete from userNotifications
  truncate table UserSettings
  truncate table UsersInActions
  truncate table UsersInTeams

